### ISSUE TITLE
Cloudshell link broken

### ISSUE THREAD

**Issue by afirth** [GoogleCloudPlatform/spinnaker-for-gcp#132] opened 2019-10-15 10:17 UTC
- Ubuntu 19/Chrome Version 77.0.3865.90
- Navigate to kube/applications/spinnaker
- Click link in description. "URL not found"
Interestingly refreshing the page then works

Initial link:
`https://console.cloud.google.com/cloudshell/editor?shellonly=true&cloudshell_git_repo=https:%2F%2Fgithub.com%2FGoogleCloudPlatform%2Fspinnaker-for-gcp.git&cloudshell_working_dir=scripts%2Fmanage&cloudshell_tutorial=landing_page_expanded.md&cloudshell_print=instructions.txt`

![image](https://user-images.githubusercontent.com/1820656/66822890-68b53a00-ef45-11e9-8080-cdc6a4f3a378.png)

Thanks for putting this together though, as someone who's started setting up spinnaker a few times for greenfields and then decided I couldn't be bothered, this repo and all the doco is incredibly helpful

**Comment by demobox** [comment] 2019-10-18 16:54
> Thanks for putting this together though, as someone who's started setting up spinnaker a few times for greenfields and then decided I couldn't be bothered, this repo and all the doco is incredibly helpful

Glad to hear, thanks!

I just tested the link by pasting it into a browser and it works for me - is the error reproducible for you?

/cc @dorbin

**Comment by afirth** [comment] 2019-10-20 10:17
yup, can repro. Pasting the link works fine. Clicking it from the GKE -> Applications sidebar doesn't. Refreshing the page then fixes it. Opening the link in a new tab also works fine. I opened the issue because I figured it probably affected more than just this one use case, but it seems isolated to the cloudshell link

**Comment by demobox** [comment] 2019-10-20 12:43
> yup, can repro. Pasting the link works fine. Clicking it from the GKE -> Applications sidebar doesn't.

Thanks for confirming! I had tried pasting straight into a browser window; will from the Applications page.

/cc @duftler

**Comment by demobox** [comment] 2019-10-21 18:13
> Clicking it from the GKE -> Applications sidebar doesn't

Just to clarify: do you mean this link?

![image](https://user-images.githubusercontent.com/223702/67231220-e331fe00-f40c-11e9-936a-610db4f3d0f8.png)

**Comment by afirth** [comment] 2019-10-22 13:46
correct. reproducible for me in a fresh install of firefox too. Only thing I see 404ing is: 
```
VM540:1 GET https://cloudusersettings-pa.clients6.google.com/v1alpha1/settings/SIDENAV_COMPACT_MODE?key=AIz[redacted]741g 404
```
which happens in both firefox and chrome.

Element is
```
<a href="https://console.cloud.google.com/cloudshell/editor?shellonly=true&amp;cloudshell_git_repo=https://github.com/GoogleCloudPlatform/spinnaker-for-gcp.git&amp;cloudshell_working_dir=scripts/manage&amp;cloudshell_tutorial=landing_page_expanded.md&amp;cloudshell_print=instructions.txt">Open management console in Cloud Shell</a>
```

It only happens if I don't open in a new tab.

**Comment by demobox** [comment] 2019-10-23 02:33
> reproducible for me in a fresh install of firefox too

Hrm, interesting - so clicking the link to open in a *new* tab works, but allowing it to open in the same tab reproducibly fails?

**Comment by afirth** [comment] 2019-10-23 17:58
Exactly. Which is weird and probably not a productive use of anyone's time to fix, but still broken.

**Comment by snipe122** [comment] 2019-10-24 18:29
Same happening for me. Maybe something wrong with the session in this state when opening link in same tab? Running Chrome 77.0.3865.120

Traffic log:

![image](https://user-images.githubusercontent.com/46678516/67514304-cd3a6c80-f69c-11e9-8020-435c26223925.png)

**Comment by demobox** [comment] 2019-10-24 22:07
> Exactly. Which is weird and probably not a productive use of anyone's time to fix, but still broken.

Does seem weird, indeed. Curious to see if anyone else runs into this too. Thanks for the additional details!

**Comment by demobox** [comment] 2019-11-01 20:32
I've passed this on to the UI team and they've said they'll look into it. Closing for now.

**Closed by demobox** 2019-11-01 20:32 UTC
