### ISSUE TITLE
Handle fiat "File" role provider

### ISSUE THREAD

**Issue by Tangeek59** [GoogleCloudPlatform/spinnaker-for-gcp#77] opened 2019-07-31 12:49 UTC
Currently testing spinnaker for GCP, I'm facing an issue with the fiat "File" role provider.

This provider need a path to a file describing each roles, I can update the role provider config.
But when I try to push it the path is not rewritten with the halyard user.

Current config in `.hal/config` :
```
    authz:
      groupMembership:
        service: EXTERNAL
        google:
          roleProviderType: GOOGLE
        github:
          roleProviderType: GITHUB
        file:
          roleProviderType: FILE
          path: /home/my_user/.hal/default/credentials/fiat-file.yaml
        ldap:
          roleProviderType: LDAP
      enabled: true
```

Error durring `push_and_apply.sh`

```
Problems in Global:
! ERROR Failed to backup user file:
  /home/my_user/.hal/default/credentials/fiat-file.yaml
- Failed to deploy Spinnaker.
```

I'm currently using a workaround with manual editing of `.hal/config` to :
```
    authz:
      groupMembership:
        service: EXTERNAL
        google:
          roleProviderType: GOOGLE
        github:
          roleProviderType: GITHUB
        file:
          roleProviderType: FILE
          path: /home/spinnaker/.hal/default/credentials/fiat-file.yaml
        ldap:
          roleProviderType: LDAP
      enabled: true
```

**Comment by duftler** [comment] 2019-07-31 12:51
Seems like the same issue as this one: https://github.com/GoogleCloudPlatform/spinnaker-for-gcp/issues/74

**Comment by Tangeek59** [comment] 2019-07-31 12:54
Yes, it seems to be linked, I see the PR resolving the issue (https://github.com/GoogleCloudPlatform/spinnaker-for-gcp/pull/76)

Do you think that `path` should be added to the test for rewriting rules ?

**Comment by duftler** [comment] 2019-07-31 12:59
yep, testing it now

**Comment by duftler** [comment] 2019-07-31 13:05
Was able to reproduce and confirm the issue is resolved with the fix contained in the referenced PR.

**Comment by duftler** [comment] 2019-07-31 13:39
The PR has been merged.

You can pick up the fix by upgrading your management environment via the included command:

![image](https://user-images.githubusercontent.com/8437718/62216618-16697180-b377-11e9-8176-03dbfa4bda8c.png)

**Closed by duftler** 2019-07-31 13:39 UTC

**Comment by Tangeek59** [comment] 2019-07-31 13:52
Fix is working, thank you ! 👍

**Comment by duftler** [comment] 2019-07-31 13:56
sweet
