### ISSUE TITLE
hal not getting installed as part of the setup.sh script

### ISSUE THREAD

**Issue by ameer00** [GoogleCloudPlatform/spinnaker-for-gcp#198] opened 2020-07-15 23:45 UTC
I am running the install setup.sh script and hal is not getting installed. Here is the error I see in the output:

```
Halyard version will be 1.33.0 
Halyard will be downloaded from gs://spinnaker-artifacts/halyard 
Halyard config will come from bucket gs://halconfig 
Halconfig will be stored at /home/student_03_1afcf960db8c/.hal/config
Uninstall script is located at /home/student_03_1afcf960db8c/.hal/uninstall.sh
Distribution Debian GNU/Linux 10 (buster) is not supported yet - please file an issue
  https://github.com/spinnaker/halyard/issues
mv: cannot stat '/etc/bash_completion.d/hal': No such file or directory
mv: cannot stat '/usr/local/bin/hal': No such file or directory
mv: cannot stat '/usr/local/bin/update-halyard': No such file or directory
mv: cannot stat '/opt/halyard': No such file or directory
sed: can't read /home/student_03_1afcf960db8c/hal/hal: No such file or directory
sed: can't read /home/student_03_1afcf960db8c/hal/hal: No such file or directory
sed: can't read /home/student_03_1afcf960db8c/hal/halyard/bin/halyard: No such file or directory
sed: can't read /home/student_03_1afcf960db8c/hal/update-halyard: No such file or directory
sed: can't read /home/student_03_1afcf960db8c/hal/update-halyard: No such file or directory
sed: can't read /home/student_03_1afcf960db8c/hal/update-halyard: No such file or directory
```

The `~/hal` folder does not contain the `hal` command and only the `spinnaker` and the `log` folder.

**Comment by plumpy** [comment] 2020-07-17 01:11
Duplicate of #196

**Closed by plumpy** 2020-07-17 01:11 UTC
